Issue #8990: Checkstyle
sevntu-checkstyle/sevntu.checkstyle pull request #841
Opened 2021-04-26 14:11 UTC by aryaniiit002

Contribution PR: https://github.com/checkstyle/checkstyle/pull/9699
https://github.com/checkstyle/checkstyle/pull/9699#issuecomment-826819142

2021-04-27 19:24 UTC, pbludov requested changes
Please fix the misleading parameter description

2021-04-27 19:24 UTC, pbludov commented on sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
> +     * @param module the locale to get the message for.
the module to load resources from.

2021-04-27 21:15 UTC, rnveach approved these changes

2021-04-28 01:54 UTC, aryaniiit002 commented on sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
> +     * @param module the locale to get the message for.
done

2021-04-28 04:20 UTC, romani commented
Please squash all commits in one, reference name of check in git commit message

2021-04-28 06:11 UTC, aryaniiit002 commented
should i send PR from separate branch and not from master?

2021-04-28 06:15 UTC, closed without merging