minor: update LogicConditionNeedOptimizationCheck to avoid false positive
sevntu-checkstyle/sevntu.checkstyle pull request #881
Opened 2022-01-19 16:58 UTC by nmancus1

From https://github.com/checkstyle/checkstyle/pull/11100

Discovered in report at https://nmancus1.github.io/issue-10848/issue-10848_check_diff_reports_2021_12_31/diff_sevntu-check-regression_part_2/index.html

2022-01-20 13:25 UTC, rnveach commented
> Builds will fail until 9.3 release.

2022-10-10 16:46 UTC, rnveach commented
@nrmancuso @romani Is this PR still blocked?
https://github.com/checkstyle/eclipse-cs/issues/339 is merged.

2022-10-10 19:05 UTC, romani commented
rebased on latest, but there are problems in UT execution

2022-10-14 19:46 UTC, rnveach commented
````
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.701 s <<< FAILURE! - in com.github.sevntu.checkstyle.internal.AllChecksTest

[ERROR] testAllInputsHaveTest  Time elapsed: 0.148 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Resource must be named after a Test like 'InputMyCheck.java' and be in the same package as the test: com/github/sevntu/checkstyle/checks/coding/InputLogicConditionNeedsOptimizationPatterns.java ==> expected: <true> but was: <false>
	at com.github.sevntu.checkstyle.internal.AllChecksTest.verifyInputFile(AllChecksTest.java:290)
	at com.github.sevntu.checkstyle.internal.AllChecksTest.lambda$testAllInputsHaveTest$4(AllChecksTest.java:185)
	at com.github.sevntu.checkstyle.internal.AllChecksTest.testAllInputsHaveTest(AllChecksTest.java:184)
````

2022-10-14 20:22 UTC, rnveach commented
````
[INFO] --- jacoco-maven-plugin:0.8.7:check (default-check) @ sevntu-checks ---
[WARNING] Rule violated for class com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck: branches covered ratio is 0.97, but expected minimum is 1.00
````

2022-10-14 20:24 UTC, rnveach requested changes

2022-10-14 20:24 UTC, rnveach commented on sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java
> +                        && firstOperand.getLastChild() != null
This 1 line is missing branch coverage.

2022-10-29 23:48 UTC, rnveach commented
@nrmancuso Can we finish this?

2022-10-30 14:52 UTC, nrmancuso commented
> @nrmancuso Can we finish this?

We should close this as syntax for pattern matching in switch has changed. We (I) made a bad decision to support a preview feature, and we will need to update grammar in main repo as this syntax is not valid any longer. I will leave this open until I create an issue in the main repo to explain all.

2022-12-10 14:22 UTC, nrmancuso commented
I have opened an issue for syntax update at https://github.com/checkstyle/checkstyle/issues/12515, we know that changes similar to what is in this PR will be required in that update.

2022-12-10 14:31 UTC, closed without merging